name: GeoBlock
main: IanSzot\GeoBlock\GeoBlock
author: IanSzot
version: 1.0-beta
api: 3.0.0

description: Block or allow players from certain countries
website: https://github.com/IanSzot/GeoBlock-PMMP